lang_list = {
    'en': {
        'profile': 'Profile',
        'alert': 'Check alerts',
        'parcel': 'My parcels', 
        'sensor': 'My devices',
        'setting': 'Change your settings',
        'logout': 'Logout',
        'password_label': 'Change your password',
        'old_password': 'Type old password here...',
        'new_password': 'Type new password here...',
        'retype': 'Retype your password',
        'setting_label': 'Change other settings here',
        'phone': 'Phone number: +',
        'email': 'Do you want to receive email alerts?',
        'sms': 'Do you want to receive sms alerts (may entail service costs)?',
        'submit_btn': 'Submit',
        'alert_table': 'User Alerts',
        'search': 'Search',
        'alert_date': 'Alert date',
        'alert_msg': 'Alert Message',
        'parcel_id': 'Parcel ID',
        'myparcel_date': 'Created',
        'myparcel_name': 'Name',
        'myparcel_crop': 'Planted crop',
        'parcel_table': 'List of parcels',
        'add_parcel': 'Add new parcel',
        'edit_parcel': 'Change parcel',
        'sensor_table': 'List of sensors',
        'mysensor_date': 'Created',
        'mysensor_id': 'Sensor ID',
        'mysensor_parcel': 'Parcel ID',
        'add_sensor': 'Add new sensor',
        'edit_sensor': 'Change sensor',
        'save': 'Save',
        'user': 'User',
        'admin': 'Admin Privilages',
        'user_table': 'Users List',
        'add_user': 'Add New User',
        'password': 'Password',
        'edit_user': 'Do you want to change user privilage to admin rights?',
        'turn_admin': 'Yes, turn to admin',
        'keep_user': 'No, keep as user',
        'active': 'Active',
        't_min': 'Lower Temperature',
        't_max': 'Upper Temperature',
        'm_min': 'Lower Moisture',
        'm_max': 'Upper Moisture',
        'season_start': 'Seasson Start at:',
        'season_end': 'Seasson Ends at:',
        'crop_table': 'Crops List',
        'crop_name': 'Crop name',
        'altitude': 'Altitude',
        'variety': 'Variety',
        'clima': 'Clima',
        'distance': 'Distance',
        'density': 'Crop density',
        'depth': 'Depth of seeds',
        'norm': 'Cultivation norm',
        'method': 'Cultivation method',
        'min_temp': 'Minimal growth temperature',
        'fertilization': 'Fertilization',
        'watering': 'Watering',
        'care': 'Care of plants',
        'protection': 'Plant protection',
        'utilization': 'Utilization',
        'harvest': 'Harvest',
        'storage': 'Storage',
        'add_crop': 'Add new crop',
        'edit_crop': 'Change crop data',
        'crop_yield': 'Expected yield per ha',
        'rain': 'Rest period after heavy rains [days]',
        'sow_complete': 'Sowed'
    },
    'sr': {
        'profile': 'Профил',
        'alert': 'Провјери обавјештења',
        'parcel': 'Моје парцеле', 
        'sensor': 'Моји уређаји',
        'setting': 'Промјена подешавања',
        'logout': 'Одјава',
        'password_label': 'Промјени лозинку',
        'old_password': 'Унеси стару лозинку...',
        'new_password': 'Унеси нову лозинку...',
        'retype': 'Понови лозинку',
        'setting_label': 'Промјена осталих подешавања',
        'phone': 'Број телефона: +',
        'email': 'Пријем порука путем емејла?',
        'sms': 'Пријем СМС порука (додатно се тарифира)?',
        'submit_btn': 'Пошаљи',
        'alert_table': 'Корисничка Обавјештења',
        'search': 'Претрага',
        'alert_date': 'Датум',
        'alert_msg': 'Обавјештење',
        'parcel_id': 'Број парцеле',
        'myparcel_date': 'Датум',
        'myparcel_name': 'Назив',
        'myparcel_crop': 'Усјев',
        'parcel_table': 'Листа парцела',
        'add_parcel': 'Додај нову парцелу',
        'edit_parcel': 'Промјени податке',
        'sensor_table': 'Списак уређаја',
        'mysensor_date': 'Датум',
        'mysensor_id': 'Број сензора',
        'mysensor_parcel': 'Број парцеле',
        'add_sensor': 'Додај нови уређај',
        'edit_sensor': 'Измјени уређај',
        'save': 'Сачувај',
        'user': 'Корисник',
        'admin': 'Администраторске привилегије',
        'user_table': 'Листа Корисника',
        'add_user': 'Додај Корисника',
        'password': 'Лозинка',
        'edit_user': 'Do you want to change user privilage to admin rights?',
        'turn_admin': 'Да, поставити као админ',
        'keep_user': 'Не, оставити као корисника',
        'active': 'Активан',
        't_min': 'Нижа Температура',
        't_max': 'Виша Температура',
        'm_min': 'Нижа Влага',
        'm_max': 'Виша Влага',
        'season_start': 'Почетак сјетве:',
        'season_end': 'Крај сјетве:',
        'crop_table': 'Листа усјева',
        'crop_name': 'Усјев',
        'altitude': 'Надморска висина',
        'variety': 'Сорта',
        'clima': 'Клима',
        'distance': 'Размак садње',
        'density': 'Густина садње',
        'depth': 'Дубина садње',
        'norm': 'Узгојне норме',
        'method': 'Узгојни метод',
        'min_temp': 'Минимална температура раста',
        'fertilization': 'Ђубрење',
        'watering': 'Наводњавање',
        'care': 'Одржавање биља',
        'protection': 'Заштита биља',
        'utilization': 'Намјена кориштења',
        'harvest': 'Берба-Жетва',
        'storage': 'Чување',
        'add_crop': 'Додати усјев',
        'edit_crop': 'Промјена сјетвених података',
        'crop_yield': 'Очекивани принос по ха',
        'rain': 'Период након пљускова [дани]',
        'sow_complete': 'Посијано'
    },
    'hr': {
        'profile': 'Profil',
        'alert': 'Provjeri poruke',
        'parcel': 'Moje Parcele', 
        'sensor': 'Moji uredjaji',
        'setting': 'Promjeni podesenja',
        'logout': 'Odjava',
        'password_label': 'Promjeni zaporku',
        'old_password': 'Utipkaj staru zaporku...',
        'new_password': 'Utipkaj novu zaporku...',
        'retype': 'Ponovi novu zaporku',
        'setting_label': 'Promjena drugih postavki',
        'phone': 'Telefonski broj: +',
        'email': 'Zelite primati elektronske obavjesti?',
        'sms': 'Zelite primati SMS obavjesti (dodatno se naplacuje)?',
        'submit_btn': 'Posalji',
        'alert_table': 'Korisnicke obavjesti',
        'search': 'Pretraga',
        'alert_date': 'Datum obavjesti',
        'alert_msg': 'Poruka',
        'parcel_id': 'Parcele ID',
        'myparcel_date': 'Datum',
        'myparcel_name': 'Naziv',
        'myparcel_crop': 'Usijev',
        'parcel_table': 'Lista parcela',
        'add_parcel': 'Dodaj novu parcelu',
        'edit_parcel': 'Izmjeni parcelu',
        'sensor_table': 'Lista senzora',
        'mysensor_date': 'Datum',
        'mysensor_id': 'Senzor ID',
        'mysensor_parcel': 'Broj parcele',
        'add_sensor': 'Dodati novi senzor',
        'edit_sensor': 'Izmjeni senzor',
        'save': 'Sacuvaj',
        'user': 'Korisnik',
        'admin': 'Administratorske privilegije',
        'user_table': 'Lista Korisnika',
        'add_user': 'Dodaj Korisnika',
        'password': 'Zaporka',
        'edit_user': 'Do you want to change user privilage to admin rights?',
        'turn_admin': 'Da, postavi za admina',
        'keep_user': 'Ne, običan korisnik',
        'active': 'Aktivan',
        't_min': 'Niža Temperatura',
        't_max': 'Viša Temperatura',
        'm_min': 'Niža Vlaga',
        'm_max': 'Viša Vlaga',
        'season_start': 'Početak sjetve:',
        'season_end': 'Kraj sjetve:',
        'crop_table': 'Lista Usjeva',
        'crop_name': 'Usjev',
        'altitude': 'Nadmorska visina',
        'variety': 'Sorta',
        'clima': 'Klima',
        'distance': 'Razmak sadnje',
        'density': 'Gustina sadnje',
        'depth': 'Dubina sadnje',
        'norm': 'Uzgojne norme',
        'method': 'Uzgojni metod',
        'min_temp': 'Minimalna temperatura za rast',
        'fertilization': 'Djubrenje',
        'watering': 'Navodnjavanje',
        'care': 'Briga za biljke',
        'protection': 'Zastita biljaka',
        'utilization': 'Primjena i koristenje',
        'harvest': 'Berba',
        'storage': 'Cuvanje',
        'add_crop': 'Dodati usjev',
        'edit_crop': 'Promjena sjetvenih podataka',
        'crop_yield': 'Ocekivani prinos po ha',
        'rain': 'Period cekanja poslije pljuskova [dani]',
        'sow_complete': 'Zasijano'
    },
    'ba': {
        'profile': 'Profil',
        'alert': 'Provjeri poruke',
        'parcel': 'Moje Parcele', 
        'sensor': 'Moji uredjaji',
        'setting': 'Promjeni podesenja',
        'logout': 'Odjava',
        'password_label': 'Promjeni zaporku',
        'old_password': 'Utipkaj staru zaporku...',
        'new_password': 'Utipkaj novu zaporku...',
        'retype': 'Ponovi novu zaporku',
        'setting_label': 'Promjena drugih postavki',
        'phone': 'Telefonski broj: +',
        'email': 'Zelite primati elektronske obavjesti?',
        'sms': 'Zelite primati SMS obavjesti (dodatno se naplacuje)?',
        'submit_btn': 'Posalji',
        'alert_table': 'Korisnicke obavjesti',
        'search': 'Pretraga',
        'alert_date': 'Datum obavjesti',
        'alert_msg': 'Poruka',
        'parcel_id': 'Parcele ID',
        'myparcel_date': 'Datum',
        'myparcel_name': 'Naziv',
        'myparcel_crop': 'Usijev',
        'parcel_table': 'Lista parcela',
        'add_parcel': 'Dodaj novu parcelu',
        'edit_parcel': 'Promjeni podatke',
        'sensor_table': 'Lista senzora',
        'mysensor_date': 'Datum',
        'mysensor_id': 'Senzor ID',
        'mysensor_parcel': 'Broj parcele',
        'add_sensor': 'Dodaj novi senzor',
        'edit_sensor': 'Promjeni senzor',
        'save': 'Snimi',
        'user': 'Korisnik',
        'admin': 'Administratorske privilegije',
        'user_table': 'Lista Korisnika',
        'add_user': 'Dodaj Korisnika',
        'password': 'Lozinka',
        'edit_user': 'Do you want to change user privilage to admin rights?',
        'turn_admin': 'Da, postavi za admina',
        'keep_user': 'Ne, običan korisnik',
        'active': 'Aktivan',
        't_min': 'Niža Temperatura',
        't_max': 'Viša Temperatura',
        'm_min': 'Niža Vlaga',
        'm_max': 'Viša Vlaga',
        'season_start': 'Početak sjetve:',
        'season_end': 'Kraj sjetve:',
        'crop_table': 'Lista Usjeva',
        'crop_name': 'Usjev',
        'altitude': 'Nadmorska visina',
        'variety': 'Sorta',
        'clima': 'Klima',
        'distance': 'Razmak sadnje',
        'density': 'Gustina sadnje',
        'depth': 'Dubina sadnje',
        'norm': 'Uzgojne norme',
        'method': 'Uzgojni metod',
        'min_temp': 'Minimalna temperatura za rast',
        'fertilization': 'Djubrenje',
        'watering': 'Navodnjavanje',
        'care': 'Briga za biljke',
        'protection': 'Zastita biljaka',
        'utilization': 'Primjena i koristenje',
        'harvest': 'Berba',
        'storage': 'Cuvanje',
        'add_crop': 'Dodati usjev',
        'edit_crop': 'Promjena sjetvenih podataka',
        'crop_yield': 'Ocekivani prinos po ha',
        'rain': 'Period cekanja poslije pljuskova [dani]',
        'sow_complete': 'Zasijano'
    }
}